import { Roboto, Geist_Mono } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Demo Next App',
  description: 'Demo NextJS app generated by create next app',
};

export default function RootLayout({ children }) {
  const links = [
    { link: '/', title: 'Home' },
    { link: '/about', title: 'About' },
    { link: '/contact', title: 'Contact' },
  ];
  return (
    // JSX
    <html lang='en'>
      <body className={`${roboto.variable} ${geistMono.variable} antialiased`}>
        <nav>
          <ul className={'flex gap-10'}>
            {links.map((link) => (
              <li key={link.title}>
                <a href={link.link} className='py-4 px-6'>
                  {link.title}
                </a>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
